### ISSUE TITLE
Cant turn off Arlec-Grid-Connect-Smart_LED-Globe-CWWW light using HA

### ISSUE THREAD

**Issue by muzzak123** [cdmonk/esphome_ArlecSmartGlobe#1]
Hi, Thx for you work with the Arlec-Grid-Connect-Smart_LED-Globe-CWWW config. I've flashed my light with it and can now do transitions, but when I try to turn it off using the Home Assistant entity the log shows
[11:53:48][D][light:273]: State: OFF
[11:53:48][D][light:303]: Transition Length: 1.0s
but nothing happens. It just stays on.
I reported it here, [https://github.com/jonathanadams/esphome-configs/issues/90](url)
and Jonathon told me to report it to you.
When I switch it on, it goes from 0 brightness up to max in 1 second but when I switch it off nothing happens. It stays on. Any ideas ?

**Comment by cdmonk** [comment]
Hi Murray.

I didn’t have any issues around that
Can you please let me know what model number your globe is and can you provide the ESPhome logs when toggling the light on and off from HA?

**Comment by cdmonk** [comment]
Don't worry. I have replicated it. The same thing happens for me I apparently never tested turning it on and off as my use case didn't require it. I assumed that it would work. Let me look at it.

**Comment by owenholloway** [comment]
Also having this issue, might need to set the PWM dimmer pin to 0 as a an off, not sure if its possible though

**Comment by Owen-Holloway101** [comment]
Oddly I'm noting that it is briefly turning off as part of the turning on sequence ....

**Comment by muzzak123** [comment]
Yes - I went back to using Tasmota. I can't use transitions but at least I can turn it off.

**Comment by cdmonk** [comment]
@Owen-Holloway101 - Agreed. And it does indeed turn off the light when i force that, however I can not seem to access the On/Off state of the light through the ESPHome API's. Additionally the ESPHome API's take care of fading on state change and they are behaving oddly at the moment. They do not fade down when turning the bulb off, But do fade up when turning it on so turning it off does nothing, then turning it on drops the brightness down to just above zero and fades up.

If I can get access to the State through the API then I can force it off.

**Comment by owenholloway** [comment]
Okay managed to get it turning on and off using the following, will start working from there

```
output:
  - platform: esp8266_pwm
    id: dimmer
    pin: GPIO5
  - platform: esp8266_pwm
    id: color_temp
    pin: GPIO13

light:
  - platform: rgbw
    name: "Arlec Smart Globe"
    white: dimmer
    red: dimmer
    green: dimmer
    blue: dimmer
```

**Comment by owenholloway** [comment]
Okay so if you are willing to go without the colour temp you can use the following for full dimming and on/off

```

output:
  - platform: esp8266_pwm
    id: dimmer
    pin: GPIO5
  - platform: esp8266_pwm
    id: color_temp
    pin: GPIO13

light:
  - platform: monochromatic
    name: "Pluto"
    output: dimmer

```

**Comment by JoeSydney** [comment]
Hi there. cwww2 works on this light. It would be good if you could update esphome-configs.io as I encountered the same issues with not being able to turn the light off.

output:
  - platform: esp8266_pwm
    id: dimmer
    pin: GPIO5
  - platform: esp8266_pwm
    id: color_temp
    pin: GPIO13

light:
  - platform: cwww2
    id: my_light
    name: 'My Light'
    color_temperature: color_temp
    brightness: dimmer
    cold_white_color_temperature: 5700 K
    warm_white_color_temperature: 3000 K

**Comment by ando023** [comment]
Hi all, I would like to confirm @JoeSydney example above as working. I have tested this with a slightly different model of the Arlec CWWW bulb (GLD110HA) and I have full OFF/ ON, Warm-Cold and Brightness control now. 

Also for those who run up against the missing platform error, you have to add the cwww2 custom_components into the root of your ESPHome directory. You can get the files from [here](https://github.com/ssieb/custom_components/tree/master/cwww2)

**Comment by ando023** [comment]
So looks like the `cwww2` component no longer works with `v2021.8.0` of ESPHome. From what I have read, it looks like they implemented a new color mode to work in Home Assistant. 

I actually noticed this as I was performing some maintenance tasks over all my ESPHome devices and found that all my bulbs in my house were no longer updating. 

The error I was seeing was; 

![](https://i.imgur.com/9P6b9Lk.png)

I have just tested with my `Arlec CWWW - GLD112HA` and it seems to be working a treat on the integrated `color_temperature` platform. 

What I found to work was the following;

```
output:
  - platform: esp8266_pwm
    id: dimmer
    pin: GPIO5
  - platform: esp8266_pwm
    id: color_temp
    pin: GPIO13
    inverted: true

light:
- platform: color_temperature
  name: "Office Light Bulb"
  color_temperature: color_temp
  brightness: dimmer
  cold_white_color_temperature: 5700 K
  warm_white_color_temperature: 3000 K
```

Thought I would include an example here as it might help someone else as it did for me.
